//using Stump.ORM;
//using Stump.ORM.SubSonic.SQLGeneration.Schema;

//namespace Database.Mariages
//{
//    [TableName("characters_spouse")]
//    public class SpouseRecord : IAutoGeneratedRecord
//    {
//        [PrimaryKey("Id", true)]
//        public int Id { get; set; }
//        public int SpouseAccountId { get; set; }
//        public int OwnerId { get; set; }
//        public string OwnerName { get; set; }
//        public int SpouseId { get; set; }
//        public string name { get; set; }
//        public long level { get; set; }
//        public sbyte breed { get; set; }
//        public sbyte sex { get; set; }
//        public sbyte alignement { get; set; }
//        public string look { get; set; }
//        public string guilldName { get; set; }
//        public int Map { get; set; }
//        public int SubArea { get; set; }
//        public bool PvPEnabled { get; set; }
//        public bool IsFighting { get; set; }
//        public bool IsNew { get; set; }
//    }
//}
