using System.Drawing;
using System.Linq;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.Items.Templates;
using Stump.Server.WorldServer.Game.Items;
using Stump.DofusProtocol.Enums;

namespace Stump.Server.WorldServer.Database.Zaap
{
    public class ChasseurRelator
    {
        public static string FetchQuery = "SELECT * FROM jobs_chasseur";
    }

    [TableName("jobs_chasseur")]
    public class ChasseurRecord : IAutoGeneratedRecord
    {
        [PrimaryKey("MonsterId")]
        public int MonsterId
        {
            get;
            set;
        }

        public int DropId
        {
            get;
            set;
        }

        public int Level
        {
            get;
            set;
        }

        public string Note
        {
            get;
            set;
        }

    }
}