create table monsters_races
(
    Id          int          not null
        primary key,
    Name        varchar(255) null,
    SuperRaceId int          not null,
    NameId      int unsigned not null
)
    engine = MyISAM
    charset = utf8;

INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (-1, 'Sin clasificar', 1, 140217);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (0, 'Invocaciones de clase', 28, 7399);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (2, 'Bandidos', 10, 7378);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (3, 'Wabbits', 8, 7357);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (4, 'Dragohuevos', 4, 7354);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (5, 'Bworks', 3, 7341);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (6, 'Goblins', 3, 7330);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (7, 'Gelatinas', 4, 7337);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (8, 'Monstruos de la noche', 11, 7352);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (9, 'Jalatós', 2, 7377);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (10, 'Plantas de los campos', 2, 7318);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (11, 'Larvas', 2, 7333);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (12, 'Kwaks', 3, 7332);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (13, 'Crujidores', 3, 7334);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (16, 'Cerdos', 3, 7344);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (17, 'Chafers', 11, 7342);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (18, 'Dopeuls de templo', 27, 78085);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (19, 'Pnjs', 10, 7372);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (20, 'Kaníbolas de Moon', 7, 556600);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (21, 'Dragopavos', 14, 139601);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (22, 'Abraknídeos', 4, 139596);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (23, 'Blops', 5, 140216);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (24, 'Animales de los campos', 5, 658232);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (25, 'Monstruos de las landas', 6, 7369);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (26, 'Guardias', 10, 7355);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (28, 'Dopeuls', 5, 658238);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (30, 'Salteadorillos', 10, 7327);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (31, 'Monstruos de las alcantarillas', 13, 747017);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (32, 'Se busca', 27, 7380);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (33, 'Píos', 13, 7388);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (34, 'Monstruos del pueblo de Pandala', 9, 7361);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (35, 'Monstruos de Pandala', 9, 7324);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (36, 'Fantasmas de Pandala', 9, 139600);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (37, 'Escarahojas', 4, 139599);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (38, 'Araknas', 4, 139597);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (39, 'Milubos', 6, 139598);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (40, 'Monstruos de las playas de Moon', 7, 556397);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (41, 'Piratas de Moon', 7, 7315);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (43, 'Monstruos de la Jungla Prohibida', 7, 556398);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (44, 'Cocodrails', 12, 7328);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (45, 'Setas', 2, 152535);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (46, 'Tofus', 2, 7390);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (47, 'Alimañas de los campos', 2, 724243);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (48, 'Monstruos de los pantanos', 12, 7350);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (49, 'Animales del bosque', 4, 7387);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (50, 'Monstruos de misión', 27, 7393);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (51, 'Cuerboks', 5, 7345);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (53, 'Fantasmas', 11, 7353);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (55, 'Plantas de Pandala', 9, 152512);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (56, 'Kitsus', 9, 7331);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (57, 'Pandawas', 9, 7396);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (59, 'Firefux', 9, 7351);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (60, 'Koalaks', 14, 7358);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (61, 'Monstruos de las cuevas', 14, 7376);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (62, 'Protectores de cereales', 15, 7322);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (63, 'Protectores de minerales', 15, 7319);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (64, 'Protectores de árboles', 15, 7316);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (65, 'Protectores de peces', 15, 7363);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (66, 'Protectores de plantas', 15, 7356);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (67, 'Minos', 16, 7329);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (68, 'Monstruos de Nawidad', 24, 7400);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (69, 'Pischis', 17, 747774);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (71, 'Monstruos de las Llanuras Herbosas', 19, 7339);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (72, 'Monstruos de la playa de coral', 19, 7335);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (73, 'Monstruo de la turbera', 19, 139749);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (74, 'Monstruos de la Oscura Jungla', 19, 78086);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (75, 'Monstruos del árbol Hakam', 19, 7323);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (76, 'Monstruos del arca de Otomai', 19, 7309);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (77, 'Monstruo del pueblo de los zoths', 19, 139619);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (78, 'Archimonstruos', 20, 214302);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (79, 'Jalamuts', 21, 214300);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (81, 'Monstruos del burgo', 21, 7311);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (82, 'Monstruos del Bosque de los Pinos Perdidos', 21, 7386);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (83, 'Güinos', 21, 214299);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (84, 'Golosotes', 21, 214298);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (85, 'Monstruos de Las Lágrimas de Uronigrido', 21, 7384);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (86, 'Monstruos de La Cuna de Alma', 21, 7385);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (87, 'Monstruos de Los Colmillos de Cristal', 21, 7349);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (88, 'Gélifux', 21, 214301);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (89, 'Monstruos del Bosque Petrificado', 21, 7368);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (90, 'Monstruos “Se busca” de Frigost', 21, 7391);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (91, 'Monstruos de misión de Frigost', 21, 7397);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (93, 'Monstruos de Kéfriho', 21, 7374);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (95, 'Bombas', 28, 7389);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (96, 'Monstruos de Vulkania', 22, 7394);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (98, 'Torres', 28, 484432);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (99, 'Espanterrores', 11, 484435);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (100, 'Invocaciones dopeuls', 28, 484453);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (101, 'Pandisidentes', 9, 484460);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (102, 'Fongos', 6, 484458);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (103, 'Encuerados', 21, 484456);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (104, 'Monstruos de las misiones de Vulkania', 22, 484454);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (105, 'Monstruos de las misiones de Nawidad', 24, 484467);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (106, 'Armadutinados', 21, 484466);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (107, 'Alquimilusionistas', 21, 484464);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (108, 'Bricoléricos', 21, 484462);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (109, 'Siniestros', 21, 484449);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (110, 'Invocaciones de monstruo', 28, 484441);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (111, 'Invocaciones de encarnación', 28, 484440);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (112, 'Prismas de alianza', 1, 484443);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (113, 'Monstruos de la isla Rokartón', 25, 484442);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (114, 'Monstruos del arzobispado', 5, 729708);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (116, 'Monstruos de misión de alineamiento', 27, 485423);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (117, 'Mercenarinos', 26, 484445);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (118, 'Monstruos de eventos', 1, 484448);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (120, 'Kanigs de los Dientes de Piedra', 5, 484452);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (121, 'Obscurantis', 29, 484451);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (122, 'Pestruces', 5, 484450);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (123, 'Puerkazos', 5, 484468);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (124, 'Perforatroces', 29, 484465);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (125, 'Divinutrofs', 29, 484463);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (126, 'Cofrefuertes', 29, 484461);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (127, 'Busca y captura de la dimensiones', 29, 484459);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (128, 'Cortesanos tenebrosos', 29, 484457);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (129, 'Maligilantes', 29, 484455);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (130, 'Necróticos', 29, 484437);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (131, 'Krobios', 21, 484436);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (132, 'Idos', 29, 484439);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (133, 'Horademonios', 29, 484438);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (134, 'Xeloforme', 29, 484446);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (135, 'Vilinsektos', 13, 486064);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (136, 'Arak-hais', 4, 514264);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (137, 'Chafers de Incarnam', 18, 530023);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (138, 'Monstruos del Templo Celeste', 18, 530024);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (139, 'Monstruos de misión de Incarnam', 18, 530025);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (140, 'Fuegos espirituales', 18, 530026);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (141, 'Jalatós de Incarnam', 18, 530027);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (142, 'Monstruos de los campos de Incarnam', 18, 530028);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (143, 'Miaufianes', 18, 530029);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (144, 'Gootas', 18, 530030);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (145, 'Setas de Incarnam', 18, 530022);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (147, 'Se busca (alineamiento)', 27, 591534);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (148, 'Gran Juego', 29, 611318);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (149, 'Zurcapulgas', 29, 611317);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (150, 'Micholobos', 29, 611316);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (152, 'Monstruos de las ruinas submarinas', 26, 634723);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (153, 'Trithones', 26, 634724);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (154, 'Servidores de lo indecible', 26, 634725);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (155, 'Mulaguas salvajes', 26, 643660);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (156, 'Busca y captura de Sufokia', 26, 649662);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (158, 'Balíes', 5, 666718);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (159, 'Autómatas de los salteadorillos', 5, 666722);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (160, 'Trools de Litneg', 5, 666721);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (162, 'Rufianes de Cania', 5, 666719);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (163, 'Bworks de Cania', 5, 666720);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (166, 'Animales del desierto', 30, 702956);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (167, 'Cacterros', 30, 698086);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (168, 'Gusanos de arena', 30, 711590);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (169, 'Malditos', 30, 713107);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (171, 'Grescazadores', 4, 722568);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (172, 'Magik Riktus', 6, 725233);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (173, 'Ghuls', 6, 724114);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (174, 'Animenfermos', 13, 724234);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (175, 'Quemaalmas', 21, 730597);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (176, 'Calcinados', 6, 737195);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (177, 'Sumergidos', 21, 737623);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (181, 'Monstruos de las playas', 17, 747775);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (182, 'Móguices', 3, 751213);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (183, 'Vuelocerontes', 1, 761926);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (184, 'Clan Martillelo', 21, 758997);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (189, 'Crocantes', 34, 789023);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (190, 'Waddictos', 34, 783529);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (191, 'Guardianes de las anomalías', 35, 789096);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (193, 'Chocomantes', 34, 783595);
INSERT INTO world.monsters_races (Id, Name, SuperRaceId, NameId) VALUES (196, 'Monstruos de misión de la isla de Pazcuak', 34, 789961);