create table interactives_templates
(
    Id             int          not null
        primary key,
    Name           varchar(255) null,
    NameId         int unsigned not null,
    ActionId       int          not null,
    DisplayTooltip tinyint      not null
)
    engine = MyISAM
    charset = utf8;

INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (1, 'Fresno', 2655, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (2, 'Sierra', 2609, 2, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (8, 'Roble', 2604, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (11, 'Mesa de confección', 2687, 2, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (12, 'Taller', 2617, 2, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (13, 'Banco', 2662, 2, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (15, 'Caldero', 2598, 2, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (16, 'Zaap', 2652, 3, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (17, 'Hierro', 2667, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (22, 'Horno', 2669, 2, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (24, 'Plata', 2616, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (25, 'Oro', 2636, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (26, 'Piedra de bauxita', 2640, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (27, 'Molde', 2685, 2, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (28, 'Tejo', 2671, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (29, 'Ébano', 2580, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (30, 'Olmo', 2646, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (31, 'Arce', 2666, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (32, 'Carpe', 2629, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (33, 'Castaño', 2601, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (34, 'Nogal', 2690, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (35, 'Cerezo silvestre', 2595, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (37, 'Piedra de kobalto', 2603, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (38, 'Trigo', 2625, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (39, 'Lúpulo', 2670, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (40, 'Molino', 2676, 2, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (41, 'Muela', 547370, 2, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (42, 'Lino', 2632, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (43, 'Cebada', 2681, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (44, 'Centeno', 2613, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (45, 'Avena', 2622, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (46, 'Cáñamo', 2627, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (47, 'Malta', 2633, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (48, 'Montón de patatas', 2688, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (49, 'Mesa para patatas', 2684, 2, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (50, 'Triturador', 2628, 2, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (52, 'Estaño', 2590, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (53, 'Piedra de cobre', 2654, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (54, 'Manganeso', 2634, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (55, 'Bronce', 2626, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (56, 'Fuente rejuvenecedora', 2677, 4, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (57, 'Yunque', 2589, 2, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (58, 'Máquina de coser', 2637, 2, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (60, 'Marmita', 2635, 7, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (61, 'Edelweiss', 2585, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (62, 'Alembique', 2583, 2, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (63, 'Trigo candeal', 2659, 1, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (64, 'Espelta', 2665, 1, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (65, 'Sorgho', 2615, 1, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (66, 'Menta salvaje', 2673, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (67, 'Trébol de 5 hojas', 599880, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (68, 'Orquídea freyesca', 2680, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (69, 'Mortero & Maza', 2674, 2, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (70, 'Puerta', 2599, 5, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (71, 'Bamga', 558250, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (72, 'Salmoon agresivo', 2597, 1, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (73, 'Pwulpo', 2605, 1, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (74, 'Trucha', 558257, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (75, 'Gobio', 558252, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (76, 'Pez gatito', 558251, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (77, 'Cangrejo', 558253, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (78, 'Pescado empanado', 558255, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (79, 'Carpa de Iem', 558259, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (80, 'Trucha de barro', 2689, 1, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (81, 'Sardina brillante', 558256, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (82, 'Algodón', 2584, 1, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (83, 'Máquina de hilar', 2668, 2, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (84, 'Pozo', 2606, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (85, 'Cofre', 2630, 6, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (86, 'Máquina de coser', 2638, 2, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (88, 'Banco de madera', 2594, 2, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (90, 'Alambique', 2582, 2, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (92, 'Yunque mágico', 2698, 2, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (93, 'Triturador Munster', 2631, 2, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (94, 'Encimera', 2641, 2, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (95, 'Encimera', 2644, 2, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (96, 'Encimera', 2642, 2, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (97, 'Encimera', 2643, 2, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (98, 'Bombú', 2620, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (99, 'Sombra extraña', 2679, 1, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (100, 'Pischis', 2675, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (101, 'Olivioleta', 2683, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (102, 'Máquina de fuerza', 2611, 1, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (103, 'Banco pirotécnico', 2657, 2, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (104, 'Kuakuá', 320683, 1, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (105, 'Basura', 2639, 6, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (106, 'Zaapi', 2600, 10, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (107, 'Yunque para escudos', 2656, 2, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (108, 'Bambú', 2623, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (109, 'Bambú oscuro', 147137, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (110, 'Bambú sagrado', 2619, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (111, 'Arroz', 2612, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (112, 'Pandoja', 2682, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (113, 'Dolomita', 2648, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (114, 'Silicato', 2614, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (115, 'Kesemueven', 2608, 11, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (116, 'Máquina de coser mágica', 2607, 2, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (117, 'Taller mágico', 2618, 2, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (118, 'Mesa mágica', 2693, 2, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (119, 'Lista de artesanos', 261283, 12, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (120, 'Cercado', 2592, 13, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (121, 'Kalipto', 544320, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (122, 'Taller de bricolaje', 2621, 2, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (127, 'Palanca', 2672, 14, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (128, 'Estatua de clase', 2678, 15, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (129, '[NO_TRAD]Any IE', 176188, 16, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (131, 'Campanilla de invierno', 2610, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (132, 'Inverluza', 558254, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (133, 'Álamo temblón', 2660, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (134, 'Frostizz', 2658, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (135, 'Obsidiana', 2664, 1, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (136, 'Valva', 2695, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (137, 'Máquina de coser de Poss''Ybel', 2691, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (138, 'Fábrica', 526532, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (139, 'Mesa de cocina de mala calidad', 2586, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (140, 'Taller de mala calidad', 2588, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (141, 'Banco de trabajo de mala calidad', 2591, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (142, 'Máquina de coser de mala calidad', 2593, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (143, 'Máquina para hacer juguetes', 76683, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (144, 'Lagar para pescado', 76684, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (145, 'Taller de empaquetado', 94353, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (146, 'Caja de regalo', 94354, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (147, 'Taller de empaquetado de regalos', 109490, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (148, 'Taller de alquimistas', 109492, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (149, 'Taller de joyeros', 109494, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (150, 'Taller de carniceros', 109475, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (151, 'Taller de carniceros y cazadores', 109474, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (152, 'Taller de escudos', 109473, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (153, 'Taller de panaderos', 109472, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (154, 'Taller de manitas', 109479, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (155, 'Taller de leñadores', 109478, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (156, 'Taller de cazadores', 109477, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (157, 'Taller de zapateros', 109476, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (158, 'Taller de forjamagos', 109481, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (159, 'Taller de herreros', 109480, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (160, 'Taller de mineros', 109482, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (161, 'Taller de campesinos', 109456, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (162, 'Taller de pescaderos', 109455, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (163, 'Taller de pescadores y pescaderos', 109458, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (164, 'Taller de pescadores', 109457, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (165, 'Taller de escultores', 109460, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (166, 'Taller de sastres', 109459, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (167, 'Arena', 109462, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (168, 'Banco', 109461, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (169, 'Bar Akudo', 109463, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (170, 'Biblioteca', 109469, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (171, 'Tienda de Nawidad', 109471, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (172, 'Dojo', 109510, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (173, 'Iglesia', 109509, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (174, 'Tienda de comestibles', 109508, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (175, 'Fabricante de esquís', 109507, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (176, 'Ayuntamiento', 109506, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (177, 'Casa de los oficios', 109505, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (178, 'Kanojedo', 109504, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (179, 'Koliseo', 109503, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (180, 'Milicia', 109513, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (181, 'Médico de Frigost', 109511, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (182, 'Taberna', 109512, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (183, 'Taberna Almenú', 109493, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (184, 'Taberna Detós', 544316, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (185, 'Taberna de Plata', 109496, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (186, 'Taberna de Djaul', 109495, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (187, 'Taberna Bagruta', 109486, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (188, 'Taberna de Jarradepalo', 109484, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (189, 'Taberna Malicia Miseria', 109489, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (190, 'Taberna La Paliza Feliz', 109499, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (191, 'Taberna de Lisa Kaya', 109500, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (192, 'Taberna de Kéfriho', 109501, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (193, 'Taberna del Bwork', 109502, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (194, 'Taberna Gatokemao', 109466, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (195, 'Taberna El Último Refugio', 201355, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (196, 'Taberna Chatarreo', 109468, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (197, 'Taberna Feubuk', 109470, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (198, 'Taberna del Pandawa Borracho', 109464, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (199, 'Taberna El Paraíso Frigosteño', 109465, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (200, 'Taberna del Pankemante', 109498, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (201, 'Taberna del Ripata', 109497, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (202, 'Templo de los gremios', 109488, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (203, 'Torre de Brakmar', 109487, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (204, 'Torre de los Archivos', 109485, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (205, 'Torre de las Órdenes', 109483, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (206, 'Submarino steamer', 116272, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (207, 'Altar', 189280, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (208, 'Krosmaster', 189279, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (209, 'Taller de Isidoro Febre', 276182, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (210, 'Taller de Al Shab', 276187, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (211, 'Taller de Frigostina', 276189, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (212, 'Taller de Igoñi Algüeros', 276188, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (213, 'Taller de Dutch', 276183, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (214, 'Taller de Borkeitri', 276181, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (215, 'Taller de Abraham Uralla', 276186, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (216, 'Taller de Clarys Togatos', 276185, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (217, 'Taller de Anita Sadimpuestos', 276179, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (218, 'Taller de Carla Garfield', 276178, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (219, 'Telar del futuro', 276180, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (220, 'Tonel de explosivos', 292275, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (221, 'Flor de otol', 292274, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (222, 'Barbacoa', 292273, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (223, 'Zanahowia fresca', 299540, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (224, 'Alambique patinado de la casa de los oficios', 299539, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (225, 'Botella de ron', 325371, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (226, 'Ascensor', 331227, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (227, 'Champiñón', 372612, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (228, 'Mesa de Bowis', 372811, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (229, 'Taller de Meriana', 372812, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (230, 'Portal de los bworks', 407668, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (231, 'Distribuidor de misiones', 415272, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (232, 'Portal', 415273, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (233, 'Cofre de oro', 415274, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (234, 'Cubito de hielo', 423445, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (235, 'Ir hacia', 423446, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (236, 'Pupitre', 434186, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (237, 'Mesa de planificación', 434187, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (238, 'Ir a la instancia A', 459729, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (239, 'Ir a la instancia B', 459730, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (240, 'Ir a la instancia C', 459728, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (241, 'Viejo cofre XXIII', 468417, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (242, 'Taller de relojero', 469679, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (243, 'Cofre XI', 469672, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (244, 'Cofre XXIII', 469673, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (245, 'Cofre XXXI', 469674, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (246, 'Cofre LIX', 469675, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (247, 'Reloj 2 minutos adelantado', 469803, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (248, 'Reloj 3 minutos retrasado', 469804, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (249, 'Reloj 7 minutos adelantado', 469805, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (250, 'Reloj 8 minutos retrasado', 469801, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (251, 'Huevos de temparak', 469802, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (252, 'Taller de los viajeros', 469800, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (253, 'Portal de los selotropes', 501844, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (254, 'Ortiga', 529497, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (255, 'Salvia', 529498, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (256, 'Ginseng', 529495, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (257, 'Belladona', 529496, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (258, 'Mandrágora', 529490, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (259, 'Avellano', 529491, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (260, 'Maíz', 529492, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (261, 'Mijo', 529493, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (262, 'Bloque de piedra', 529494, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (263, 'Lucio', 571713, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (264, 'Kralamar', 571715, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (265, 'Anguila', 571720, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (266, 'Dorada exploradora', 571721, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (267, 'Perca', 571718, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (268, 'Raya', 571719, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (269, 'Rape', 571710, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (270, 'Tiburón martillhoz', 571711, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (271, 'Lubina mericana', 571712, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (272, 'Bacaladilla', 571716, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (273, 'Tenca', 571717, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (274, 'Pez espadón', 571714, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (275, 'Yunque Mulic Bere', 585151, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (276, 'Banco de trabajo de Mulic Bere', 585154, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (277, 'Taller de Mulic Bere', 585155, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (278, 'Ensamblador de Mulic Bere', 585152, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (279, 'Taller de Mago de Zo', 585153, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (280, 'Plataforma hipermaga', 595369, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (281, 'Trébol de 4 hojas', 610089, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (282, 'Indicar una salida', 601012, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (283, 'Miautún', 616180, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (284, 'Escalera', 649675, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (285, 'Puerta blindada', 649673, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (286, 'Taller indecible', 649671, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (287, 'Acuacia', 652600, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (288, 'Salikronia', 652592, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (289, 'Quisnoa', 652596, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (290, 'Lapa', 652598, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (291, 'Sepiolita', 652601, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (292, 'Mesa de trabajo', 657642, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (293, 'Sepiolita', 657645, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (294, 'Acuacia', 657643, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (295, 'Salikronia', 657647, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (296, 'Quisnoa', 657646, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (297, 'Lapa', 657644, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (298, 'Taller de Natacha Manka', 666636, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (299, 'Huevos frescos', 666637, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (300, 'Casa', 719595, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (301, 'Arena de torneo', 719596, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (302, 'Seta acuática', 726303, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (303, 'Agripnita matasueño', 727803, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (304, 'Agripnita matasueño tostada', 727806, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (305, 'Pueblo en miniatura', 729631, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (306, 'Máquina de coser astrubiense', 733500, 0, 0);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (307, 'Güino de Galaethiel', 733501, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (308, 'Regalo sorpresa', 733999, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (309, 'Caja chirriante', 742198, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (310, 'Pócima sorpresa', 742106, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (311, 'Taller improvisado', 743948, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (312, 'Puerta del territorio de los dioses', 744365, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (313, 'Mercadillo de recursos', 749268, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (314, 'Mercadillo de equipables', 749269, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (315, 'Mercadillo de consumibles', 749270, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (316, '[!] Panneau directionnel', 750586, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (317, 'Cristal', 756671, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (318, 'Mercadillo de runas', 756939, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (319, 'Mercadillo de criaturas', 756942, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (320, 'Mercadillo de almas', 756945, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (321, 'Lino del destino', 774666, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (322, 'Envoltorio', 789791, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (323, 'Taller de Nafs', 792497, 0, 1);
INSERT INTO world.interactives_templates (Id, Name, NameId, ActionId, DisplayTooltip) VALUES (324, 'Pasaje inestable', 796116, 0, 1);