create table mounts
(
    Name              mediumtext not null,
    Sex               tinyint    not null,
    TemplateId        int        not null,
    Experience        bigint     not null,
    GivenExperience   tinyint    not null,
    Stamina           int        not null,
    Maturity          int        not null,
    Energy            int        not null,
    Serenity          int        not null,
    Love              int        not null,
    ReproductionCount int        not null,
    BehaviorsCSV      mediumtext not null,
    OwnerId           int        null,
    OwnerName         mediumtext null,
    PaddockId         int        null,
    IsInStable        tinyint    not null,
    StoredSince       datetime   null,
    Id                int        not null
        primary key
)
    engine = MyISAM
    charset = utf8;

create index OwnerId
    on mounts (OwnerId);

create index PaddockId
    on mounts (PaddockId);

INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 60, 0, 0, 0, 0, 7358, 0, 0, 0, '', 168, '[PAPA]', null, 0, null, 1);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Frost', 0, 16, 1355215, 0, 0, 0, 5558, 0, 0, 0, '', 208, 'Cernunnos', null, 0, null, 2);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 70623, 5, 0, 0, 7358, 0, 0, 0, '', 297, 'Dibs', null, 0, null, 3);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 66, 2233166, 0, 0, 0, 6158, 0, 0, 0, '', 389, 'Netero', 1, 1, null, 4);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 66, 3496440, 0, 0, 0, 6158, 0, 0, 0, '', 368, 'Maalgor', null, 0, null, 6);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 66, 4670149, 0, 0, 0, 6158, 0, 0, 0, '', 365, 'Melofia', null, 0, null, 7);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 66, 3941602, 0, 0, 0, 6158, 0, 0, 0, '', 367, 'Matrona', null, 0, null, 8);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 66, 3409751, 0, 0, 0, 6158, 0, 0, 0, '', 366, 'Brann', null, 0, null, 5);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Petunia', 1, 61, 1576264, 50, 0, 0, 6158, 0, 0, 0, '', 437, 'Aion', null, 0, null, 9);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 15, 1814375, 0, 0, 0, 5558, 0, 0, 0, '', 757, 'Kiuji-ocra', null, 0, null, 13);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 15, 1925609, 0, 0, 0, 5558, 0, 0, 0, '', 863, 'Kiuji-hiper', null, 0, null, 10);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 15, 1811473, 0, 0, 0, 5558, 0, 0, 0, '', 760, 'Kiuji-eni', null, 0, null, 12);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 15, 1950817, 0, 0, 0, 5558, 0, 0, 0, '', 759, 'Kiuji-feca', null, 0, null, 11);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 15, 1275903, 0, 0, 0, 5558, 0, 0, 0, '', 682, 'Kiuji-yop', null, 0, null, 14);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 66, 917825, 10, 0, 0, 6158, 0, 0, 0, '', 390, 'Nikaydo', null, 0, null, 15);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Volkruste', 0, 195, 3136614, 90, 0, 0, 29958, 0, 0, 0, '', 593, 'Pascalin', null, 0, null, 16);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 66, 407908, 0, 0, 0, 6158, 0, 0, 0, '', 391, 'Cuillere', null, 0, null, 17);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 45, 1376713, 0, 0, 0, 6158, 0, 0, 0, '', 470, 'Ozahef', null, 0, null, 18);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 15, 120017, 20, 0, 0, 5558, 0, 0, 0, '', 389, 'Netero', null, 0, null, 20);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 15, 768750, 30, 0, 0, 5558, 0, 0, 0, '', 399, 'Madara', null, 0, null, 19);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 53, 2560192, 0, 0, 0, 4958, 0, 0, 0, '', 747, 'Rayo-Maxuka', null, 0, null, 31);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 191, 7364308, 0, 0, 0, 29958, 0, 0, 0, '', 446, 'Cra-Barty', null, 0, null, 22);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 15, 1146677, 90, 0, 0, 5558, 0, 0, 0, '', 535, 'Sogoren', null, 0, null, 23);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 155, 2272675, 0, 0, 0, 4958, 0, 0, 0, '', 545, 'Givrax-Fleche', 1, 1, null, 24);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 15, 2357728, 0, 0, 0, 5558, 0, 0, 0, '', 642, 'Zatsu-Nogitsu', null, 0, null, 26);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 15, 2357728, 0, 0, 0, 5558, 0, 0, 0, '', 544, 'Givrax-Piege', null, 0, null, 27);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 15, 2570499, 0, 0, 0, 5558, 0, 0, 0, '', 545, 'Givrax-Fleche', null, 0, null, 28);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 15, 2558998, 0, 0, 0, 5558, 0, 0, 0, '', 543, 'Givrax-Pelle', null, 0, null, 25);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 83, 1038348, 90, 0, 0, 7358, 0, 0, 0, '', 795, 'Eltontotom', null, 0, null, 32);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 86, 1351750, 0, 0, 0, 7358, 0, 0, 0, '', 606, 'Queen-Archery', null, 0, null, 30);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 9, 1290873, 0, 0, 0, 6158, 0, 0, 0, '', 752, 'Bearca', null, 0, null, 33);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 124, 0, 0, 0, 0, 4958, 0, 0, 0, '', 643, '[Choji]', null, 0, null, 34);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 67, 1345462, 0, 0, 0, 6158, 0, 0, 0, '', 647, 'Vash', null, 0, null, 35);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 61, 1338677, 0, 0, 0, 6158, 0, 0, 0, '', 755, 'Bearop', null, 0, null, 36);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 16, 1345410, 0, 0, 0, 5558, 0, 0, 0, '', 759, 'Kiuji-feca', 1, 1, null, 37);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 68, 1589917, 0, 0, 0, 6158, 0, 0, 0, '', 644, 'Vroomvroom', null, 0, null, 38);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 67, 29552, 90, 0, 0, 6158, 0, 0, 0, '', 802, 'Labitch', null, 0, null, 39);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 9, 1267694, 0, 0, 0, 6158, 0, 0, 0, '', 787, 'Zobnubile', null, 0, null, 43);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 61, 1267694, 90, 0, 0, 6158, 0, 0, 0, '', 783, 'Ecaflibustier', null, 0, null, 40);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 67, 1267694, 90, 0, 0, 6158, 0, 0, 0, '', 780, 'Enirixe', null, 0, null, 41);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 67, 1497892, 0, 0, 0, 6158, 0, 0, 0, '', 784, 'Pandabstinence', null, 0, null, 42);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 61, 1638260, 0, 0, 0, 6158, 0, 0, 0, '', 758, 'Kiuji-sacro', null, 0, null, 44);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 68, 1267694, 90, 0, 0, 6158, 0, 0, 0, '', 785, 'Iopulent', null, 0, null, 45);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 68, 1474147, 0, 0, 0, 6158, 0, 0, 0, '', 875, 'Bearwa', null, 0, null, 46);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 67, 1291018, 0, 0, 0, 6158, 0, 0, 0, '', 874, 'Bearip', null, 0, null, 47);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('elloco', 1, 217, 2395782, 0, 0, 0, 29958, 0, 0, 0, '', 981, 'Glifitos', null, 0, null, 48);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 58, 3277159, 0, 0, 0, 7358, 0, 0, 0, '', 635, 'Hypza', null, 0, null, 49);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 67, 2649540, 0, 0, 0, 6158, 0, 0, 0, '', 1065, 'Iren', null, 0, null, 50);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Glaceon', 1, 66, 2761772, 0, 0, 0, 6158, 0, 0, 0, '', 435, 'Boreas', null, 0, null, 352);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 67, 1385267, 0, 0, 0, 6158, 0, 0, 0, '', 1106, 'Bearsa', null, 0, null, 353);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 54, 47064, 90, 0, 0, 4958, 0, 0, 0, '', 1097, 'Hitchi', null, 0, null, 354);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 61, 2159853, 0, 0, 0, 6158, 0, 0, 0, '', 1089, 'Lennak', null, 0, null, 355);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 9, 1292572, 90, 0, 0, 6158, 0, 0, 0, '', 687, 'Kanaky-monpays', null, 0, null, 356);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 59, 45247319, 0, 0, 0, 7358, 0, 0, 0, '', 1318, 'Luxia', null, 0, null, 357);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 190, 0, 0, 0, 0, 29958, 0, 0, 0, '', 1301, 'Boubou', null, 0, null, 362);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 181, 0, 0, 0, 0, 29958, 0, 0, 0, '', 1302, 'Rox-boubou', null, 0, null, 363);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 61, 4563380, 5, 0, 0, 6158, 0, 0, 0, '', 1323, 'Twinky', null, 0, null, 364);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 181, 122045, 90, 0, 0, 29958, 0, 0, 0, '', 1401, 'Dangerous', null, 0, null, 366);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 284, 0, 0, 0, 0, 29958, 0, 0, 0, '', 1381, '[Jfin]', null, 0, null, 367);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 125, 1032014, 90, 0, 0, 4958, 0, 0, 0, '', 1380, 'Pitux', null, 0, null, 369);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 143, 0, 0, 0, 0, 4958, 0, 0, 0, '', 1425, 'Nouvo', 1, 1, null, 370);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 181, 0, 0, 0, 0, 29958, 0, 0, 0, '', 1425, 'Nouvo', 1, 1, null, 371);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 59, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1425, 'Nouvo', null, 0, null, 372);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 16, 6871242, 0, 0, 0, 5558, 0, 0, 0, '', 1506, 'Shiroi', null, 0, null, 373);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1493, 'Piaf', null, 0, null, 375);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 181, 7087533, 0, 0, 0, 29958, 0, 0, 0, '', 1598, 'Boubou', null, 0, null, 382);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 181, 6778721, 0, 0, 0, 29958, 0, 0, 0, '', 1599, 'Rox-boubou', null, 0, null, 383);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 186, 420890, 90, 0, 0, 29958, 0, 0, 0, '', 1608, 'San-Cafeine', null, 0, null, 385);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 67, 1416792, 0, 0, 0, 6158, 0, 0, 0, '', 1665, 'Ogg-berserk', null, 0, null, 386);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 309140, 0, 0, 0, 7358, 0, 0, 0, '', 1549, 'Pai-Teemo', null, 0, null, 388);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 49, 19352, 90, 0, 0, 4958, 0, 0, 0, '', 1674, 'Osahero', null, 0, null, 389);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 16, 1468056, 0, 0, 0, 5558, 0, 0, 0, '', 1675, 'Wraz', null, 0, null, 390);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Kult', 0, 67, 574353, 5, 0, 0, 6158, 0, 0, 0, '', 1682, 'Kult', null, 0, null, 391);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 61, 146728, 0, 0, 0, 6158, 0, 0, 0, '', 1684, 'Jiwagaku', null, 0, null, 393);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 445);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 494);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 493);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 492);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 491);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 490);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 489);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 488);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 487);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 486);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 485);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 484);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 483);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 482);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 481);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 480);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 479);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 478);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 477);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 476);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 475);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 474);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 473);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 472);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 471);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 470);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 469);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 468);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 467);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 466);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 465);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 464);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 463);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 462);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 461);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 460);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 459);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 458);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 457);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 456);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 455);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 454);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 453);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 452);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 451);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 450);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 449);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 448);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 447);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 89, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 446);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 395);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 444);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 443);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 442);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 441);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 440);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 439);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 438);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 437);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 436);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 435);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 434);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 433);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 432);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 431);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 430);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 429);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 428);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 427);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 426);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 425);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 424);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 423);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 422);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 421);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 420);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 419);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 418);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 417);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 416);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 415);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 414);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 413);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 412);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 411);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 410);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 409);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 408);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 407);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 406);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 405);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 404);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 403);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 402);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 401);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 400);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 399);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 398);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 397);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 396);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1704, 'Yex-banque', 1, 1, null, 394);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 37, 0, 90, 0, 0, 6158, 0, 0, 0, '', 1640, 'Pierre-Jean', null, 0, null, 495);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 91, 0, 0, 0, 0, 4958, 0, 0, 0, '', 1539, 'Soufx-Arc', null, 0, null, 497);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 91, 0, 0, 0, 0, 4958, 0, 0, 0, '', 1666, 'Soufx-Puni', null, 0, null, 498);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 57, 216610, 90, 0, 0, 7358, 0, 0, 0, '', 1721, 'Lucy', null, 0, null, 500);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 88, 0, 0, 0, 0, 7358, 0, 0, 0, '', 1582, 'Konic', null, 0, null, 504);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 15, 68102790, 0, 0, 0, 5558, 0, 0, 0, '', 1655, 'Day-Tergent', null, 0, null, 505);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 15, 5759412, 0, 0, 0, 5558, 0, 0, 0, '', 1778, 'Day-Tente', null, 0, null, 506);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 178, 1297378, 0, 0, 0, 29958, 0, 0, 0, '', 1563, 'Pitux', null, 0, null, 509);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 15, 1556161, 0, 0, 0, 5558, 0, 0, 0, '', 1827, 'Lira', 9, 1, null, 510);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 15, 1424484, 0, 0, 0, 5558, 0, 0, 0, '', 1843, 'Winnie', null, 0, null, 511);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 15, 2121986, 0, 0, 0, 5558, 0, 0, 0, '', 1858, 'Day-Capite', null, 0, null, 513);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 15, 2121986, 0, 0, 0, 5558, 0, 0, 0, '', 1859, 'Day-Tritu', null, 0, null, 512);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 15, 9205175, 0, 0, 0, 5558, 0, 0, 0, '', 1536, 'Kingstone', null, 0, null, 514);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 15, 496903, 0, 0, 0, 5558, 0, 0, 0, '', 1545, 'Pirefewom', null, 0, null, 515);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 186, 1557403, 0, 0, 0, 29958, 0, 0, 0, '', 1884, 'Megazordan', null, 0, null, 516);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 125, 4253001, 0, 0, 0, 4958, 0, 0, 0, '', 1839, 'Zayken', null, 0, null, 517);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 15, 11115940, 0, 0, 0, 5558, 0, 0, 0, '', 1913, 'Flo-Archer', null, 0, null, 518);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 44, 6739140, 0, 0, 0, 3758, 0, 0, 0, '', 1982, 'Yoshh', null, 0, null, 520);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 44, 6739140, 0, 0, 0, 3758, 0, 0, 0, '', 1981, 'Yoosh', null, 0, null, 521);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 67, 9485038, 0, 0, 0, 6158, 0, 0, 0, '', 1994, 'Loutre', null, 0, null, 522);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 145, 3732919, 0, 0, 0, 4958, 0, 0, 0, '', 1998, 'Tagzz', null, 0, null, 523);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 67, 4147706, 0, 0, 0, 6158, 0, 0, 0, '', 2013, 'Yossh', null, 0, null, 525);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 213, 1969622, 0, 0, 0, 29958, 0, 0, 0, '', 2028, 'Joji', null, 0, null, 526);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 15, 1368411, 0, 0, 0, 5558, 0, 0, 0, '', 2093, 'Cassiere', null, 0, null, 528);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 191, 0, 90, 0, 0, 29958, 0, 0, 0, '', 1949, 'Jean-Noel', null, 0, null, 529);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 15, 1442420, 0, 0, 0, 5558, 0, 0, 0, '', 2096, 'Missiere', null, 0, null, 530);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 15, 1276417, 0, 0, 0, 5558, 0, 0, 0, '', 2099, 'Codraco', null, 0, null, 532);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 15, 1264917, 0, 0, 0, 5558, 0, 0, 0, '', 2100, 'Lahel', null, 0, null, 533);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 1, 89, 373639, 0, 0, 0, 7358, 0, 0, 0, '', 2164, 'Yupie', null, 0, null, 534);
INSERT INTO world.mounts (Name, Sex, TemplateId, Experience, GivenExperience, Stamina, Maturity, Energy, Serenity, Love, ReproductionCount, BehaviorsCSV, OwnerId, OwnerName, PaddockId, IsInStable, StoredSince, Id) VALUES ('Anonyme', 0, 276, 5395496, 90, 0, 0, 29958, 0, 0, 0, '', 1822, 'Likadi', null, 0, null, 536);