create table characters
(
    Id                               int auto_increment
        primary key,
    CreationDate                     datetime                 not null,
    LastUsage                        datetime                 null,
    Name                             mediumtext               not null,
    AccountId                        int          default 0   not null,
    Breed                            int                      not null,
    Sex                              int                      not null,
    Head                             int                      not null,
    DefaultLookString                mediumtext               null,
    LastLookString                   mediumtext               null,
    CustomEntityLookString           mediumtext               null,
    CustomLookActivated              tinyint                  not null,
    TitleId                          smallint                 null,
    TitleParam                       mediumtext               not null,
    TitlesCSV                        mediumtext               null,
    Ornament                         smallint                 null,
    OrnamentsCSV                     mediumtext               null,
    EmotesCSV                        mediumtext               null,
    SmileyPacksCSV                   mediumtext               null,
    FinishMovesCSV                   mediumtext               null,
    IdolsCSV                         mediumtext               null,
    MapId                            int                      not null,
    CellId                           smallint                 not null,
    Direction                        int                      not null,
    BaseHealth                       int                      not null,
    DamageTaken                      int                      not null,
    AP                               int                      not null,
    MP                               int                      not null,
    Prospection                      int                      not null,
    Strength                         int                      not null,
    Chance                           int                      not null,
    Vitality                         int                      not null,
    Wisdom                           int                      not null,
    Intelligence                     int                      not null,
    Agility                          int                      not null,
    PermanentAddedStrength           int                      not null,
    PermanentAddedChance             int                      not null,
    PermanentAddedVitality           int                      not null,
    PermanentAddedWisdom             int                      not null,
    PermanentAddedIntelligence       int                      not null,
    PermanentAddedAgility            int                      not null,
    Kamas                            int                      not null,
    Experience                       bigint                   not null,
    EnergyMax                        smallint                 not null,
    Energy                           smallint                 not null,
    StatsPoints                      smallint unsigned        not null,
    SpellsPoints                     smallint     default 0   null,
    AlignmentSide                    int                      not null,
    AlignmentValue                   tinyint                  not null,
    Honor                            smallint unsigned        not null,
    Dishonor                         smallint unsigned        not null,
    PvPEnabled                       tinyint                  not null,
    RankId                           int          default 0   not null,
    RankExp                          int          default 0   not null,
    SpawnMapId                       int                      null,
    WarnOnConnection                 tinyint                  not null,
    WarnOnGuildConnection            tinyint                  not null,
    WarnOnLevel                      tinyint                  not null,
    MuteUntil                        datetime                 null,
    MandatoryChanges                 tinyint                  not null,
    PossibleChanges                  tinyint                  not null,
    LeftFightId                      int                      null,
    safe200                          int          default 0   not null,
    safeitem                         int                      not null,
    PrestigeRank                     int                      not null,
    PrestigeHonor                    int                      not null,
    Xpepique                         int                      not null,
    ArenaRank_3vs3                   int                      not null,
    ArenaMaxRank_3vs3                int                      not null,
    ArenaDailyMatchsWon_3vs3         int                      not null,
    ArenaDailyDate_3vs3              datetime                 not null,
    ArenaDailyMaxRank_3vs3           int                      not null,
    ArenaDailyMatchsCount_3vs3       int                      not null,
    ArenaDailyDate_1vs1              datetime                 not null,
    ArenaRank_1vs1                   int                      not null,
    ArenaDailyMatchsWon_1vs1         int                      not null,
    ArenaMaxRank_1vs1                int                      not null,
    ArenaDailyMaxRank_1vs1           int                      not null,
    ArenaDailyMatchsCount_1vs1       int                      not null,
    ArenaPenalityDate                datetime                 not null,
    EquippedMount                    int                      null,
    UseHarnessColor                  tinyint      default 1   not null,
    IsRiding                         tinyint                  not null,
    PlayerLifeStatus                 int                      not null,
    SmileyMoodId                     int                      not null,
    DeletedDate                      datetime                 null,
    KnownZaapsBin                    longblob                 null,
    HasExoPa                         int                      not null,
    HasExoPm                         int                      not null,
    HasExoPo                         int                      not null,
    CharacterToSeekName              varchar(255)             null,
    AgressionPenalityDate            datetime                 not null,
    RankWin                          int                      not null,
    RankLose                         int                      not null,
    RankReward                       datetime                 null on update CURRENT_TIMESTAMP,
    NumberOfPnjFound                 int                      null,
    WinPvm                           int                      not null,
    LosPvm                           int                      not null,
    WinPvp                           int                      not null,
    LosPvp                           int                      not null,
    IsInIncarnation                  int          default 0   not null,
    IncarnationId                    int                      null,
    IsInHavenBag                     int          default 0   not null,
    HavenBagsCSV                     varchar(255) default '2' null,
    HavenBagOwnerId                  int                      not null,
    MapBeforeHavenBagId              int                      not null,
    CellBeforeHavenBagId             int                      not null,
    ArenaRank                        varchar(255)             null,
    ArenaMaxRank                     varchar(255)             null,
    ArenaMinRank                     varchar(255)             null,
    ArenaDailyDate                   datetime                 null,
    ArenaDailyMaxRank                varchar(255)             null,
    ArenaDailyMinRank                varchar(255)             null,
    ArenaDailyMatchsCount            varchar(255)             null,
    ArenaDailyMatchsWon              varchar(255)             null,
    FinishedAchievementsCSV          mediumtext               null,
    AcceptedFinishedAchievementsCSV  mediumtext               null,
    UnAcceptedAchievementsCSV        mediumtext               null,
    FinishedAchievementObjectivesCSV mediumtext               null,
    RunningAchievementObjectivesCSV  mediumtext               null,
    AchievementRewardsBin            mediumtext               null,
    AchievementPoints                int          default 0   null,
    LeagueId                         int                      not null,
    FirstConnection                  int                      null,
    ChallengesCount                  int          default 0   null,
    ChallengesInDungeonCount         int          default 0   null,
    OwnedRuneAmount                  int          default 0   null,
    BackDungeon                      int          default 0   null,
    DungeonDoneCSV                   mediumtext               null,
    AscensionStair                   int          default 0   not null,
    ControlIA                        int                      null,
    MaxStatsPvp                      int                      null,
    ForceStatsPointRetirePvp         int                      null,
    ChanceStatsPointRetirePvp        int                      null,
    IntelligenceStatsPointRetirePvp  int                      null,
    AgiliteStatsPointRetirePvp       int                      null,
    TreasureSearch                   int          default 0   null,
    TreasureMapCoffre                int                      null,
    TreasureTimeStart                datetime                 null,
    TreasureIndice                   int                      null,
    GM                               int          default 0   not null
)
    engine = MyISAM
    charset = utf8;

INSERT INTO world.characters (Id, CreationDate, LastUsage, Name, AccountId, Breed, Sex, Head, DefaultLookString, LastLookString, CustomEntityLookString, CustomLookActivated, TitleId, TitleParam, TitlesCSV, Ornament, OrnamentsCSV, EmotesCSV, SmileyPacksCSV, FinishMovesCSV, IdolsCSV, MapId, CellId, Direction, BaseHealth, DamageTaken, AP, MP, Prospection, Strength, Chance, Vitality, Wisdom, Intelligence, Agility, PermanentAddedStrength, PermanentAddedChance, PermanentAddedVitality, PermanentAddedWisdom, PermanentAddedIntelligence, PermanentAddedAgility, Kamas, Experience, EnergyMax, Energy, StatsPoints, SpellsPoints, AlignmentSide, AlignmentValue, Honor, Dishonor, PvPEnabled, RankId, RankExp, SpawnMapId, WarnOnConnection, WarnOnGuildConnection, WarnOnLevel, MuteUntil, MandatoryChanges, PossibleChanges, LeftFightId, safe200, safeitem, PrestigeRank, PrestigeHonor, Xpepique, ArenaRank_3vs3, ArenaMaxRank_3vs3, ArenaDailyMatchsWon_3vs3, ArenaDailyDate_3vs3, ArenaDailyMaxRank_3vs3, ArenaDailyMatchsCount_3vs3, ArenaDailyDate_1vs1, ArenaRank_1vs1, ArenaDailyMatchsWon_1vs1, ArenaMaxRank_1vs1, ArenaDailyMaxRank_1vs1, ArenaDailyMatchsCount_1vs1, ArenaPenalityDate, EquippedMount, UseHarnessColor, IsRiding, PlayerLifeStatus, SmileyMoodId, DeletedDate, KnownZaapsBin, HasExoPa, HasExoPm, HasExoPo, CharacterToSeekName, AgressionPenalityDate, RankWin, RankLose, RankReward, NumberOfPnjFound, WinPvm, LosPvm, WinPvp, LosPvp, IsInIncarnation, IncarnationId, IsInHavenBag, HavenBagsCSV, HavenBagOwnerId, MapBeforeHavenBagId, CellBeforeHavenBagId, ArenaRank, ArenaMaxRank, ArenaMinRank, ArenaDailyDate, ArenaDailyMaxRank, ArenaDailyMinRank, ArenaDailyMatchsCount, ArenaDailyMatchsWon, FinishedAchievementsCSV, AcceptedFinishedAchievementsCSV, UnAcceptedAchievementsCSV, FinishedAchievementObjectivesCSV, RunningAchievementObjectivesCSV, AchievementRewardsBin, AchievementPoints, LeagueId, FirstConnection, ChallengesCount, ChallengesInDungeonCount, OwnedRuneAmount, BackDungeon, DungeonDoneCSV, AscensionStair, ControlIA, MaxStatsPvp, ForceStatsPointRetirePvp, ChanceStatsPointRetirePvp, IntelligenceStatsPointRetirePvp, AgiliteStatsPointRetirePvp, TreasureSearch, TreasureMapCoffre, TreasureTimeStart, TreasureIndice, GM) VALUES (1, '2021-09-10 09:51:45', '2021-09-10 10:17:35', 'Test', 0, 8, 1, 121, '{1|81,2132|1=16103775,2=15430419,3=16777185,4=14432786,5=14432786|140}', '{1|81,2132|1=16103775,2=15430419,3=16777185,4=14432786,5=14432786|140}', null, 0, null, '', '', null, '', '1', '0', '1|True', '', 153090, 413, 2, 70, 0, 6, 3, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100, 1440, 10000, 10000, 10, 0, 0, 0, 0, 0, 0, 1, 0, null, 1, 0, 1, null, 0, 0, null, 0, 0, 0, 0, 0, 0, 0, 0, '0001-01-01 00:00:00', 0, 0, '0001-01-01 00:00:00', 0, 0, 0, 0, 0, '0001-01-01 00:00:00', null, 0, 0, 0, 0, null, 0x0000231F00002F160000352500003B3100003D26000234230002413800025C1200DC05070140070101AC0404033A9B49033A9D29041400030416080204600000050E0B010540091005401301054204010542050A0542071705B0080405F0020605FA0201067C000006DC0A0106E602070728040307840B1B0878160E08CC0C09092C0505092C0600092E030309500A020958000809B4000E09B4080009B4100009CC001009D806070A4004120A5404020AB802000B1402010B6408020BA400000BA40800, 0, 0, 0, null, '0001-01-01 00:00:00', 0, 0, '0001-01-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, '1;2', 0, 0, 0, null, null, null, null, null, null, null, null, '424,422,385', '', '', '2314,2312,2374', null, null, 3, 6, 0, 0, 0, 0, 0, '', 0, 0, 0, 0, 0, 0, 0, 0, null, '0001-01-01 00:00:00', null, 0);